#!/usr/bin/env python3
"""lore2lua: convert lore sources into packed-string Lua databases.

Domains: items, recipes (extracted from the game client by
tools/data-extractor/extract.py, which calls convert_items /
convert_recipes in-process with in-memory records) and bestiary
(the wiki database). Stdlib only.

Usage:
  python3 tools/data-extractor/extract.py <game_dir>        # items + recipes
  lua5.4 .tools/bestiary_dump.lua . .tools/bestiary_source.json
  python3 tools/lore2lua/convert.py --data <lore_dir> --out src/Data --db bestiary

Bestiary pipeline (local tooling in .tools/): browser_bestiary_dump.js
fetches the wiki (raw dump JSON); src/Encyclopedia/data.lua is the
maintained entry database built from it; bestiary_dump.lua + this packer
turn data.lua into the packed blobs the plugin actually loads
(src/Data/Bestiary). data.lua itself is no longer imported at runtime --
it is the packing source. NOTE: bestiary (and nodes) still read the
legacy XML layout from --data; porting them to game extraction is
pending (see tools/data-extractor/README.md).
"""
import argparse
import os
import re
import sys
import time
import unicodedata
import xml.etree.ElementTree as ET

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from codec import b93, u93, width_for, emit_blob  # noqa: E402

LANGS = ["de", "en", "es", "fr", "ru"]
ITEM_BASE = 1879000000
GENERATED_HEADER = (
    "-- GENERATED by LUI data tools -- DO NOT EDIT\n"
    "-- Source: LOTRO game client data\n"
)


def fold(name):
    """Search normalization: lowercase + strip combining accents (é -> e)."""
    out = []
    for ch in unicodedata.normalize("NFD", name.lower()):
        if not unicodedata.combining(ch):
            out.append(ch)
    return unicodedata.normalize("NFC", "".join(out))


_TEMPLATE_REF = re.compile(r"\$\{([^}:|]*)(?::([^}|]*)[^}]*)?\}")
_GENDER_TAGS = re.compile(r"\[[^\]]*\]")


def display_sort_text(label):
    """Collation text for a display label: gender templates ${VAR:a|b}
    sort as their first variant, bare ${VAR} refs as nothing ('$' would
    otherwise clump every templated name before all plain names)."""
    if "${" not in label:
        return label
    text = _TEMPLATE_REF.sub(lambda m: m.group(2) or "", label)
    return _GENDER_TAGS.sub("", text)


def parse_labels(data_dir, lang, db, raw_keys=False):
    path = os.path.join(data_dir, "labels", lang, db + ".xml")
    labels = {}
    if not os.path.exists(path):
        return labels
    for _, el in ET.iterparse(path):
        if el.tag == "label":
            key = el.get("key")
            if raw_keys:
                labels[key] = el.get("value")
            elif key.isdigit():
                labels[int(key)] = el.get("value")
            el.clear()
    return labels


def parse_enum(data_dir, name):
    """enums/<name>.xml -> { code: label-key-or-literal }"""
    path = os.path.join(data_dir, "enums", name + ".xml")
    entries = {}
    for _, el in ET.iterparse(path):
        if el.tag == "entry":
            entries[int(el.get("code"))] = el.get("name")
    return entries


def lua_string(s):
    return '"%s"' % s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def write_file(out_dir, name, parts):
    """Emit a data module usable both by Turbine `import` (registers into the
    _G.LoreData namespace) and by standalone `dofile` (returns the table)."""
    path = os.path.join(out_dir, name)
    domain = os.path.basename(out_dir)
    reg_key = "%s.%s" % (domain, name[:-4])
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(GENERATED_HEADER)
        f.write("local D = {}\n")
        for p in parts:
            f.write(p)
        f.write('_G.LoreData = _G.LoreData or {}\n')
        f.write('_G.LoreData[%s] = D\n' % lua_string(reg_key))
        f.write("return D\n")
    return os.path.getsize(path)


def byte_len(s):
    return len(s.encode("utf-8"))


def build_names_by_lang(data_dir, db, langs, ids, en_fallback):
    """Per-language display names aligned to ids; en baked in where missing."""
    labels_en = parse_labels(data_dir, "en", db)
    en_names, missing_en = [], 0
    for n, i in enumerate(ids):
        name = labels_en.get(i) or en_fallback[n]
        if name is None:
            missing_en += 1
            name = ""
        en_names.append(name)

    names_by_lang, baked_report = {}, {}
    for lang in langs:
        if lang == "en":
            names_by_lang[lang] = en_names
            baked_report[lang] = 0
            continue
        lab = parse_labels(data_dir, lang, db)
        names, baked = [], 0
        for n, i in enumerate(ids):
            v = lab.get(i)
            if v is None or v == "":
                v = en_names[n]
                baked += 1
            names.append(v)
        names_by_lang[lang] = names
        baked_report[lang] = baked
    return names_by_lang, baked_report, missing_en


# a 2-char needle matching more than this share of a domain's entries is
# baked into D.STOP2 and treated as "still typing" by the runtime
STOP2_SHARE = 0.05


def emit_lang_files(out_dir, ids, names_by_lang, langs, search_mask=None):
    """labels_<lang> (LBL/LOFF), names_<lang> (NAME/NOFF, sorted) and search_<lang> (SRCH/SOFF) per language.

    search_mask: optional list of booleans aligned to ids; False entries get
    empty folded search text (offsets stay aligned, the entry just never
    matches). Used to keep never-searched records out of the search blobs."""
    count = len(ids)
    ord_width = width_for(count)
    sizes = {}
    for lang in langs:
        names = names_by_lang[lang]

        lbl_blob = "".join(names)
        loff, p = [], 1
        for v in names:
            loff.append(p)
            p += byte_len(v)
        loff.append(p)
        loff_width = width_for(p)
        loff_blob = "".join(b93(x, loff_width) for x in loff)
        sizes["labels_%s.lua" % lang] = write_file(out_dir, "labels_%s.lua" % lang, [
            "D.loff_width = %d\n" % loff_width,
            emit_blob("LBL", lbl_blob),
            emit_blob("LOFF", loff_blob),
        ])

        by_name = {}
        for n, v in enumerate(names):
            if v and "\t" not in v and "\n" not in v:
                by_name.setdefault(v, []).append(n + 1)
        sorted_names = sorted(by_name)
        parts, noffs, p = [], [], 1
        for v in sorted_names:
            entry = "\n%s\t%s" % (v, "".join(b93(o, ord_width) for o in by_name[v]))
            noffs.append(p)
            parts.append(entry)
            p += byte_len(entry)
        name_blob = "".join(parts) + "\n"
        noff_width = width_for(p)
        noff_blob = "".join(b93(x, noff_width) for x in noffs)
        sizes["names_%s.lua" % lang] = write_file(out_dir, "names_%s.lua" % lang, [
            "D.ord_width = %d\n" % ord_width,
            "D.noff_width = %d\n" % noff_width,
            "D.entry_count = %d\n" % len(sorted_names),
            emit_blob("NAME", name_blob),
            emit_blob("NOFF", noff_blob),
        ])

        # type-ahead search blob: folded names in ordinal order + offsets
        folded = [fold(v) if search_mask is None or search_mask[n] else ""
                  for n, v in enumerate(names)]
        srch_blob = "\n".join(folded)
        soff, p = [], 1
        for v in folded:
            soff.append(p)
            p += byte_len(v) + 1
        soff.append(p)
        soff_width = width_for(p)
        soff_blob = "".join(b93(x, soff_width) for x in soff)
        # stop bigrams: 2-char needles matching more than STOP2_SHARE of
        # the entries. A cold runtime seed scan for one of those costs
        # tens of ms and filters out nearly nothing, so evaluate_domain
        # treats them as "still typing" instead of scanning
        bigram_hits = {}
        for text in folded:
            entry_bigrams = set()
            data = text.encode("utf-8")
            for k in range(len(data) - 1):
                pair = data[k:k + 2]
                # printable ASCII only: multi-byte pairs never get close
                # to the share threshold and would need encoding care
                if 32 <= pair[0] <= 126 and 32 <= pair[1] <= 126:
                    entry_bigrams.add(pair)
            for bigram in entry_bigrams:
                bigram_hits[bigram] = bigram_hits.get(bigram, 0) + 1
        threshold = len(folded) * STOP2_SHARE
        stop2 = sorted(b for b, hits in bigram_hits.items() if hits > threshold)
        sizes["search_%s.lua" % lang] = write_file(out_dir, "search_%s.lua" % lang, [
            "D.soff_width = %d\n" % soff_width,
            emit_blob("SRCH", srch_blob),
            emit_blob("SOFF", soff_blob),
            "D.STOP2 = { %s }\n" % ", ".join(
                "[%s]=true" % lua_string(b.decode("ascii")) for b in stop2),
        ])

    return sizes, ord_width


def print_report(baked_report, missing_en, sizes, langs, count, t0):
    if missing_en:
        print("WARNING: %d records have no en label at all" % missing_en)
    print("label fallback baked from en:")
    for lang in langs:
        if lang != "en":
            print("  %s: %d of %d" % (lang, baked_report[lang], count))
    print("emitted files:")
    total = 0
    for name in sorted(sizes):
        total += sizes[name]
        print("  %-18s %8.2f MB" % (name, sizes[name] / 1e6))
    print("  %-18s %8.2f MB" % ("TOTAL", total / 1e6))
    print("done in %.1fs\n" % (time.time() - t0))


# ---------------------------------------------------------------- items ----

def parse_items(data_dir):
    path = os.path.join(data_dir, "items.xml")
    items = {}
    for _, el in ET.iterparse(path):
        if el.tag == "item":
            key = int(el.get("key"))
            items[key] = (
                el.get("quality"),
                int(el.get("level") or 0),
                int(el.get("class") or 0),
                el.get("category"),
                el.get("slot"),
                el.get("icon"),
                el.get("name"),
                int(el.get("minLevel") or 0),
                el.get("requiredClass"),
                int(el.get("maxLevel") or 0),
            )
            el.clear()
    return items


def items_from_records(records):
    """Game-extracted item records ({id: {field: value}}, from
    tools/data-extractor/extract_items.py): same tuples as parse_items,
    plus per-language names ({id: {lang: name}})."""
    items, names = {}, {}
    for key, v in records.items():
        items[int(key)] = (
            v.get("quality"),
            v.get("level") or 0,
            v.get("class") or 0,
            v.get("category"),
            v.get("slot"),
            v.get("icon"),
            v.get("name"),
            v.get("minLevel") or 0,
            v.get("requiredClass"),
            v.get("maxLevel") or 0,
        )
        names[int(key)] = {k[5:]: val for k, val in v.items()
                           if k.startswith("name_")}
    return items, names


def build_names_by_lang_records(json_names, langs, ids, en_fallback):
    """build_names_by_lang equivalent fed from extractor records."""
    en_names, missing_en = [], 0
    for n, i in enumerate(ids):
        name = en_fallback[n]
        if name is None:
            missing_en += 1
            name = ""
        en_names.append(name)
    names_by_lang, baked_report = {}, {}
    for lang in langs:
        if lang == "en":
            names_by_lang[lang] = en_names
            baked_report[lang] = 0
            continue
        names, baked = [], 0
        for n, i in enumerate(ids):
            v = json_names.get(i, {}).get(lang)
            if v is None or v == "":
                v = en_names[n]
                baked += 1
            names.append(v)
        names_by_lang[lang] = names
        baked_report[lang] = baked
    return names_by_lang, baked_report, missing_en


def parse_traceries(data_dir):
    """item id -> (socket type, min LI item level, max LI item level,
    uniqueness channel)."""
    traceries = {}
    for _, el in ET.iterparse(os.path.join(data_dir, "traceries.xml")):
        if el.tag == "tracery":
            traceries[int(el.get("itemId"))] = (
                int(el.get("type")),
                int(el.get("minItemLevel") or 0),
                int(el.get("maxItemLevel") or 0),
                int(el.get("uniquenessChannel") or 0),
            )
    return traceries


BUCKETS = ["equipment", "consumable", "resource", "housing", "tracery"]
EQUIP_CATS = {"ARMOUR", "WEAPON", "LEGENDARY_ITEM", "LEGENDARY_ITEM2",
              "LEGENDARY_WEAPON", "LEGENDARY_WEAPON2", "ESSENCE"}
CONSUME_KW = ("food", "drink", "potion", "draught", "salve", "scroll of",
              "battle scroll", "hope token", "firework", "festival token",
              "tomes", "perks", "pipeweed")
RESOURCE_KW = ("resource", "ingredient", "craft", "component", "relic",
               "tool", "dye", "device", "trophy")


def _classify_items(items, data_dir, aux=None):
    """id -> bucket code (0 = not browsable). Priority: equipment >
    consumable > resource > housing; authoritative sources before keyword
    heuristics. Recipe scrolls are consumables (you use them to learn);
    the runtime groups their per-tier classes into one Type filter entry."""
    if aux is not None:
        consumable_ids = aux["consumable_ids"]
        recipes = aux["recipes"]
        cls_name = {code: label.lower()
                    for code, label in aux["class_labels"]["en"].items()}
        tracery_ids = set(aux["traceries"])
    else:
        consumable_ids = set()
        for _, el in ET.iterparse(os.path.join(data_dir, "consumables.xml")):
            if el.tag == "consumable":
                consumable_ids.add(int(el.get("identifier")))
                el.clear()
        recipes = parse_recipes(data_dir)
        cls_enum = parse_enum(data_dir, "ItemClass")
        cls_lab = parse_labels(data_dir, "en", "enum-ItemClass", raw_keys=True)
        cls_name = {code: (cls_lab.get(k) or k).lower()
                    for code, k in cls_enum.items()}
        tracery_ids = set(parse_traceries(data_dir))

    resource_ids = set()
    scroll_ids = set()
    for r in recipes.values():
        if r["pack"]:
            resource_ids.add(r["pack"])
        if r["scroll"]:
            scroll_ids.add(r["scroll"])
        for v in r["versions"]:
            for iid, _q in v["ing"]:
                resource_ids.add(iid)
            for iid, _q, _b in v["opt"]:
                resource_ids.add(iid)

    buckets = {}
    counts = {"equipment": 0, "consumable": 0, "resource": 0, "housing": 0,
              "tracery": 0, "other": 0}
    for iid, it in items.items():
        _q, _lvl, cls, cat, slot, _icon, _name, _minlvl, _reqcls, _maxlvl = it
        label = cls_name.get(cls, "")
        if iid in tracery_ids:
            bucket = 5
        elif slot is not None or cat in EQUIP_CATS:
            bucket = 1
        elif (iid in consumable_ids or iid in scroll_ids
              or label.startswith("recipe")
              or any(k in label for k in CONSUME_KW)):
            bucket = 2
        elif iid in resource_ids or any(k in label for k in RESOURCE_KW):
            bucket = 3
        elif label.startswith("home:"):
            bucket = 4
        else:
            bucket = 0
        buckets[iid] = bucket
        counts[BUCKETS[bucket - 1] if bucket else "other"] += 1
    print("buckets:", counts)
    return buckets


def convert_items(data_dir, out_dir, langs, records=None, aux=None):
    """records/aux: in-memory game-extracted data (tools/data-extractor);
    when None, the legacy XML dumps from data_dir are used."""
    t0 = time.time()
    json_names = None
    if records is not None:
        items, json_names = items_from_records(records)
    else:
        items = parse_items(data_dir)
    ids = sorted(items)
    count = len(ids)
    print("parsed items: %d records (%.1fs)" % (count, time.time() - t0))
    bucket_by_id = _classify_items(items, data_dir, aux)

    def enum_table(idx):
        values = sorted({v[idx] for v in items.values() if v[idx] is not None})
        return values, {v: i + 1 for i, v in enumerate(values)}

    quality_vals, quality_code = enum_table(0)
    category_vals, category_code = enum_table(3)
    slot_vals, slot_code = enum_table(4)

    pool_vals = sorted({v[5] for v in items.values() if v[5] is not None})
    pool_code = {v: i + 1 for i, v in enumerate(pool_vals)}
    print("icon pool: %d unique composites" % len(pool_vals))

    coded = []
    for i in ids:
        q, lvl, cls, cat, slot, icon, _name, min_level, _reqcls, _maxlvl = items[i]
        coded.append((
            quality_code.get(q, 0), lvl, cls, category_code.get(cat, 0),
            slot_code.get(slot, 0), pool_code.get(icon, 0), min_level,
            bucket_by_id[i],
        ))

    base_id = ids[0]
    id_width = width_for(ids[-1] - base_id)
    field_names = ["quality", "level", "class", "category", "slot", "icon", "min_level", "bucket"]
    n_fields = len(field_names)
    widths = [width_for(max(c[k] for c in coded)) for k in range(n_fields)]
    stride = sum(widths)

    ids_blob = "".join(b93(i - base_id, id_width) for i in ids)
    rec_blob = "".join(
        "".join(b93(c[k], widths[k]) for k in range(n_fields)) for c in coded
    )

    pool_blob = "".join(pool_vals)
    poff, p = [], 1
    for v in pool_vals:
        poff.append(p)
        p += len(v)
    poff.append(p)
    poff_width = width_for(p)
    poff_blob = "".join(b93(x, poff_width) for x in poff)

    for n, i in enumerate(ids):
        pos = n * stride
        at = 0
        for k in range(n_fields):
            if u93(rec_blob, pos + at, widths[k]) != coded[n][k]:
                raise AssertionError("round-trip mismatch id %d field %d" % (i, k))
            at += widths[k]
        if u93(ids_blob, n * id_width, id_width) != i - base_id:
            raise AssertionError("round-trip mismatch in IDS at %d" % i)
    print("round-trip: all %d records verified" % count)

    os.makedirs(out_dir, exist_ok=True)
    sizes = {}
    sizes["records.lua"] = write_file(out_dir, "records.lua", [
        emit_blob("IDS", ids_blob),
        emit_blob("REC", rec_blob),
        emit_blob("POOL", pool_blob),
        emit_blob("POFF", poff_blob),
    ])

    en_fallback = [items[i][6] for i in ids]
    if json_names is not None:
        names_by_lang, baked_report, missing_en = build_names_by_lang_records(
            json_names, langs, ids, en_fallback)
    else:
        names_by_lang, baked_report, missing_en = build_names_by_lang(
            data_dir, "items", langs, ids, en_fallback)
    # bucket-0 ("other") items are never text-searched: the Encyclopedia
    # searches within the browsable bucket lists only, so their folded
    # search text is dead weight (~35% of the blob)
    search_mask = [bucket_by_id[i] != 0 for i in ids]
    lang_sizes, _ = emit_lang_files(out_dir, ids, names_by_lang, langs, search_mask)
    sizes.update(lang_sizes)

    # localized ItemClass names (used codes only) + per-bucket class lists
    used_classes = sorted({items[i][2] for i in ids})
    if aux is not None:
        class_labels = aux["class_labels"]
        en_class_label = class_labels["en"]
    else:
        cls_enum = parse_enum(data_dir, "ItemClass")
        en_cls = parse_labels(data_dir, "en", "enum-ItemClass", raw_keys=True)
        # labels are keyed by the enum name whether it is a "key:..."
        # reference or a literal ("WoPower" -> "Word of Power"); always
        # prefer the localized label
        class_labels = {}
        for lang in langs:
            lab = parse_labels(data_dir, lang, "enum-ItemClass", raw_keys=True)
            class_labels[lang] = {
                code: (lab.get(key) or en_cls.get(key) or key)
                for code, key in cls_enum.items()}
        en_class_label = class_labels["en"]
    unlabeled = [c for c in used_classes if c and c not in en_class_label]
    if unlabeled:
        print("WARNING: %d item classes missing from ItemClass enum" % len(unlabeled))
    cls_parts = ["D.CLASSES = {\n"]
    for lang in langs:
        entries = []
        for code in used_classes:
            value = class_labels[lang].get(code)
            if value is None:
                value = en_class_label.get(code)
            if value is not None:
                entries.append("[%d]=%s" % (code, lua_string(value)))
        cls_parts.append("%s = { %s },\n" % (lang, ", ".join(entries)))
    cls_parts.append("}\n")

    # official localized quality names, keyed by the tuple's enum strings
    # (the game displays LEGENDARY as "Epic"/"Epos" etc. -- never hand-write
    # these)
    if aux is not None:
        quality_labels = aux["quality_labels"]
        quality_keys = sorted(quality_labels["en"])
    else:
        quality_entries = []
        for _, el in ET.iterparse(os.path.join(data_dir, "enums", "ItemQuality.xml")):
            if el.tag == "entry":
                quality_entries.append((el.get("key"), el.get("name")))
        en_quality = parse_labels(data_dir, "en", "enum-ItemQuality", raw_keys=True)
        quality_labels = {}
        for lang in langs:
            lab = parse_labels(data_dir, lang, "enum-ItemQuality", raw_keys=True)
            quality_labels[lang] = {
                qkey: (lab.get(label_key) or en_quality.get(label_key) or qkey)
                for qkey, label_key in quality_entries}
        quality_keys = [qkey for qkey, _ in quality_entries]
    cls_parts.append("D.QUALITIES = {\n")
    for lang in langs:
        entries = []
        for qkey in quality_keys:
            value = quality_labels[lang].get(qkey) or quality_labels["en"].get(qkey) or qkey
            entries.append('["%s"] = %s' % (qkey, lua_string(value)))
        cls_parts.append("%s = { %s },\n" % (lang, ", ".join(entries)))
    cls_parts.append("}\n")

    bucket_classes = {b: set() for b in range(1, len(BUCKETS) + 1)}
    for i in ids:
        b = bucket_by_id[i]
        if b:
            bucket_classes[b].add(items[i][2])
    cls_parts.append("D.BUCKET_CLASSES = {\n")
    for b in range(1, len(BUCKETS) + 1):
        cls_parts.append("%s = { %s },\n" % (
            BUCKETS[b - 1], ", ".join(str(c) for c in sorted(bucket_classes[b]))))
    cls_parts.append("}\n")

    # per-tier recipe classes ("Recipe: Weaponsmith Tier 9", ~100 codes):
    # the Type dropdown shows them as one grouped "Recipes" entry
    recipe_class_codes = sorted(
        c for c in bucket_classes[2]
        if en_class_label.get(c, "").lower().startswith("recipe"))
    cls_parts.append("D.RECIPE_CLASSES = { %s }\n" % ", ".join(
        str(c) for c in recipe_class_codes))

    # per-language, per-bucket class-code order for the Type dropdown,
    # sorted by the localized label (recipe classes excluded: the
    # browser inserts their grouped entry itself; unlabeled codes
    # excluded: the dropdown never shows them)
    recipe_class_set = set(recipe_class_codes)
    cls_parts.append("D.CLASS_ORDER = {\n")
    for lang in langs:
        def class_label(code):
            return class_labels[lang].get(code) or en_class_label.get(code)
        bucket_parts = []
        for b in range(1, len(BUCKETS) + 1):
            codes = [c for c in bucket_classes[b]
                     if c and c not in recipe_class_set
                     and class_label(c) is not None]
            codes.sort(key=lambda c: (fold(display_sort_text(class_label(c))),
                                      class_label(c), c))
            bucket_parts.append("%s = { %s }" % (
                BUCKETS[b - 1], ", ".join(str(c) for c in codes)))
        cls_parts.append("%s = { %s },\n" % (lang, ", ".join(bucket_parts)))
    cls_parts.append("}\n")

    # runtime fold map: non-ASCII chars -> folded ascii, so typed needles
    # fold exactly like the build-time search blobs
    fold_pairs = {}
    for lang in langs:
        for name in names_by_lang[lang]:
            for ch in name:
                if ord(ch) >= 128:
                    f = fold(ch)
                    if f != ch:
                        fold_pairs[ch] = f
    cls_parts.append("D.FOLD = {\n")
    for ch in sorted(fold_pairs):
        cls_parts.append("[%s] = %s,\n" % (lua_string(ch), lua_string(fold_pairs[ch])))
    cls_parts.append("}\n")
    sizes["classes.lua"] = write_file(out_dir, "classes.lua", cls_parts)

    # per-language, per-bucket ordinal permutations sorted by display label
    # (folded-alphabetical): tab listings iterate these, zero runtime sorting
    bucket_ord_w = width_for(count)
    for lang in langs:
        names = names_by_lang[lang]
        parts = ["D.ord_width = %d\n" % bucket_ord_w]
        for b in range(1, len(BUCKETS) + 1):
            ordinals = [n + 1 for n, i in enumerate(ids) if bucket_by_id[i] == b]
            ordinals.sort(key=lambda o: (fold(display_sort_text(names[o - 1])),
                                         names[o - 1]))
            parts.append(emit_blob("B_" + BUCKETS[b - 1].upper(),
                                   "".join(b93(o, bucket_ord_w) for o in ordinals)))
        sizes["buckets_%s.lua" % lang] = write_file(out_dir, "buckets_%s.lua" % lang, parts)

    # tracery metadata side table: per tracery ordinal the LI item-level
    # band it sockets into, the uniqueness channel and the player class
    # (requiredClass attr; socket type 21 is Mariner, added without the
    # attr). Sorted ordinal keys + fixed stride, bsearch at runtime.
    if aux is not None:
        traceries = aux["traceries"]
        # class enum: EN labels are the requiredClass key strings
        player_class_labels = aux["player_class_labels"]
        class_id_by_name = {label: code for code, label
                            in player_class_labels["en"].items()}
        class_en_names = player_class_labels["en"]
    else:
        traceries = parse_traceries(data_dir)
        class_defs = []
        for _, el in ET.iterparse(os.path.join(data_dir, "classes.xml")):
            if el.tag == "class" and el.get("key"):
                class_defs.append((int(el.get("id")), el.get("key"), el.get("name")))
        class_id_by_name = {}
        for cid, ckey, cname in class_defs:
            class_id_by_name[ckey] = cid
            class_id_by_name[cname] = cid

    entries = []
    used_class_ids = []
    class_idx_by_id = {}
    for n, i in enumerate(ids):
        info = traceries.get(i)
        if info is None:
            continue
        ttype, min_il, max_il, channel = info
        req = items[i][8]
        if req is None and ttype == 21:
            req = "Mariner"
        class_idx = 0
        if req is not None:
            cid = class_id_by_name[req]
            if class_idx_by_id.get(cid) is None:
                used_class_ids.append(cid)
                class_idx_by_id[cid] = len(used_class_ids)
            class_idx = class_idx_by_id[cid]
        # max usable character level (min is the records' min_level field);
        # min_il is the tracery's base iLvl, max_il its enhancement cap
        entries.append((n + 1, min_il, max_il, channel, class_idx, items[i][9]))

    il_w = width_for(max(max(e[2] for e in entries), 1))
    ch_w = width_for(max(max(e[3] for e in entries), 1))
    t_parts = [
        "D.count = %d\n" % len(entries),
        "D.ord_width = %d\n" % bucket_ord_w,
        "D.il_width = %d\n" % il_w,
        "D.ch_width = %d\n" % ch_w,
        emit_blob("T_ORD", "".join(b93(e[0], bucket_ord_w) for e in entries)),
        emit_blob("T_REC", "".join(
            b93(e[1], il_w) + b93(e[2], il_w) + b93(e[3], ch_w) + b93(e[4], 1) + b93(e[5], il_w)
            for e in entries)),
    ]
    # localized player class names, indexed by the per-entry class index
    t_parts.append("D.CLASSES = {\n")
    if aux is not None:
        for lang in langs:
            names = [lua_string(player_class_labels[lang].get(cid)
                                or class_en_names[cid])
                     for cid in used_class_ids]
            t_parts.append("%s = { %s },\n" % (lang, ", ".join(names)))
    else:
        en_class_lab = parse_labels(data_dir, "en", "classes")
        for lang in langs:
            lab = parse_labels(data_dir, lang, "classes")
            names = []
            for cid in used_class_ids:
                names.append(lua_string(lab.get(cid) or en_class_lab.get(cid)
                                        or [d for d in class_defs if d[0] == cid][0][2]))
            t_parts.append("%s = { %s },\n" % (lang, ", ".join(names)))
    t_parts.append("}\n")
    sizes["traceries.lua"] = write_file(out_dir, "traceries.lua", t_parts)
    print("traceries side table: %d entries, %d classes" % (len(entries), len(used_class_ids)))

    sizes["manifest.lua"] = write_file(out_dir, "manifest.lua", [
        "D.count = %d\n" % count,
        "D.base_id = %d\n" % base_id,
        "D.id_width = %d\n" % id_width,
        "D.stride = %d\n" % stride,
        "D.poff_width = %d\n" % poff_width,
        "D.fields = { %s }\n" % ", ".join(lua_string(f) for f in field_names),
        "D.widths = { %s }\n" % ", ".join(str(w) for w in widths),
        "D.enums = {\n"
        + "quality = { %s },\n" % ", ".join(lua_string(v) for v in quality_vals)
        + "category = { %s },\n" % ", ".join(lua_string(v) for v in category_vals)
        + "slot = { %s },\n" % ", ".join(lua_string(v) for v in slot_vals)
        + "}\n",
        "D.langs = { %s }\n" % ", ".join(lua_string(v) for v in langs),
    ])
    print_report(baked_report, missing_en, sizes, langs, count, t0)


# -------------------------------------------------------------- recipes ----

def parse_recipes(data_dir):
    path = os.path.join(data_dir, "recipes.xml")
    recipes = {}
    for _, el in ET.iterparse(path):
        if el.tag == "recipe":
            rid = int(el.get("id"))
            r = {
                "name": el.get("name"),
                "profession": el.get("profession"),
                "tier": int(el.get("tier")),
                "category": int(el.get("category") or 0),
                "xp": int(el.get("xp") or 0),
                "cooldown": int(el.get("cooldown") or 0),
                "guild": el.get("guild") == "true",
                "single_use": el.get("singleUse") == "true",
                "scroll": 0, "pack": 0, "pack_count": 0,
                "versions": [],
            }
            sc = el.find("scrollItem")
            if sc is not None:
                r["scroll"] = int(sc.get("itemId"))
            ip = el.find("ingredientPack")
            if ip is not None:
                r["pack"] = int(ip.get("itemId"))
                r["pack_count"] = int(ip.get("count") or 1)
            for rr in el.findall("recipeResult"):
                v = {"crit": int(rr.get("baseCriticalChance") or 0),
                     "ing": [], "opt": [], "res": [], "cres": []}
                for ing in rr.findall("ingredient"):
                    it = ing.find("ingredientItem")
                    iid = int(it.get("itemId"))
                    qty = int(ing.get("quantity") or 1)
                    if ing.get("optional") == "true":
                        v["opt"].append((iid, qty, int(ing.get("criticalChanceBonus") or 0)))
                    else:
                        v["ing"].append((iid, qty))
                for res in rr.findall("result"):
                    it = res.find("resultItem")
                    iid = int(it.get("itemId"))
                    qty = int(res.get("quantity") or 1)
                    if res.get("critical") == "true":
                        v["cres"].append((iid, qty))
                    else:
                        v["res"].append((iid, qty))
                r["versions"].append(v)
            recipes[rid] = r
            el.clear()
    return recipes


def convert_recipes(data_dir, out_dir, langs, records=None, aux=None):
    t0 = time.time()
    recipes = records if records is not None else parse_recipes(data_dir)
    ids = sorted(recipes)
    count = len(ids)
    print("parsed recipes: %d records (%.1fs)" % (count, time.time() - t0))

    # Flag reciprocal conversion recipes (craft-XP "scraps"/processing pairs):
    # recipe A produces X from Y while recipe B produces Y from X. These form
    # 2-cycles in the crafting graph; the runtime must never expand material
    # trees through them.
    producers = {}
    for rid, r in recipes.items():
        for v in r["versions"]:
            ings = {i for i, _q in v["ing"]}
            for res_item, _q in v["res"]:
                producers.setdefault(res_item, []).append((rid, ings))
    conversion_count = 0
    for rid, r in recipes.items():
        conv = False
        for v in r["versions"]:
            results = {i for i, _q in v["res"]}
            for ing, _q in v["ing"]:
                for rid2, ings2 in producers.get(ing, []):
                    if rid2 != rid and ings2 & results:
                        conv = True
        r["conversion"] = conv
        if conv:
            conversion_count += 1
    print("conversion (2-cycle) recipes flagged: %d" % conversion_count)

    profession_vals = sorted({r["profession"] for r in recipes.values()})
    profession_code = {v: i + 1 for i, v in enumerate(profession_vals)}

    def item_off(iid):
        if iid == 0:
            return 0
        off = iid - ITEM_BASE
        if off <= 0:
            raise AssertionError("item id %d below base" % iid)
        return off

    # width maxes over the whole domain
    mx = {"category": 0, "xp": 0, "cooldown": 0, "item": 0, "qty": 0,
          "bonus": 0, "crit": 0, "n": 0, "pack_count": 0, "tier": 0}
    for r in recipes.values():
        mx["category"] = max(mx["category"], r["category"])
        mx["xp"] = max(mx["xp"], r["xp"])
        mx["cooldown"] = max(mx["cooldown"], r["cooldown"])
        mx["tier"] = max(mx["tier"], r["tier"])
        mx["pack_count"] = max(mx["pack_count"], r["pack_count"])
        mx["item"] = max(mx["item"], item_off(r["scroll"]), item_off(r["pack"]))
        mx["n"] = max(mx["n"], len(r["versions"]))
        for v in r["versions"]:
            mx["crit"] = max(mx["crit"], v["crit"])
            mx["n"] = max(mx["n"], len(v["ing"]), len(v["opt"]), len(v["res"]), len(v["cres"]))
            for iid, q in v["ing"] + v["res"] + v["cres"]:
                mx["item"] = max(mx["item"], item_off(iid))
                mx["qty"] = max(mx["qty"], q)
            for iid, q, b in v["opt"]:
                mx["item"] = max(mx["item"], item_off(iid))
                mx["qty"] = max(mx["qty"], q)
                mx["bonus"] = max(mx["bonus"], b)
    if min(r["cooldown"] for r in recipes.values()) < 0:
        raise AssertionError("negative cooldown found; add bias handling")

    W = {
        "profession": width_for(len(profession_vals)),
        "tier": width_for(mx["tier"]),
        "category": width_for(mx["category"]),
        "xp": width_for(mx["xp"]),
        "cooldown": width_for(mx["cooldown"]),
        "flags": 1,
        "item": width_for(mx["item"]),
        "qty": width_for(mx["qty"]),
        "bonus": width_for(mx["bonus"]),
        "crit": width_for(mx["crit"]),
        "n": width_for(mx["n"]),
        "pack_count": width_for(mx["pack_count"]),
    }

    def encode_recipe(r):
        parts = [
            b93(profession_code[r["profession"]], W["profession"]),
            b93(r["tier"], W["tier"]),
            b93(r["category"], W["category"]),
            b93(r["xp"], W["xp"]),
            b93(r["cooldown"], W["cooldown"]),
            b93((1 if r["guild"] else 0) + (2 if r["single_use"] else 0)
                + (4 if r["conversion"] else 0), W["flags"]),
            b93(item_off(r["scroll"]), W["item"]),
            b93(item_off(r["pack"]), W["item"]),
            b93(r["pack_count"], W["pack_count"]),
            b93(len(r["versions"]), W["n"]),
        ]
        for v in r["versions"]:
            parts.append(b93(v["crit"], W["crit"]))
            parts.append(b93(len(v["ing"]), W["n"]))
            parts.append(b93(len(v["opt"]), W["n"]))
            parts.append(b93(len(v["res"]), W["n"]))
            parts.append(b93(len(v["cres"]), W["n"]))
            for iid, q in v["ing"]:
                parts.append(b93(item_off(iid), W["item"]) + b93(q, W["qty"]))
            for iid, q, b in v["opt"]:
                parts.append(b93(item_off(iid), W["item"]) + b93(q, W["qty"]) + b93(b, W["bonus"]))
            for iid, q in v["res"]:
                parts.append(b93(item_off(iid), W["item"]) + b93(q, W["qty"]))
            for iid, q in v["cres"]:
                parts.append(b93(item_off(iid), W["item"]) + b93(q, W["qty"]))
        return "".join(parts)

    encoded = [encode_recipe(recipes[i]) for i in ids]
    data_blob = "".join(encoded)
    offs, p = [], 1
    for e in encoded:
        offs.append(p)
        p += len(e)
    offs.append(p)
    off_width = width_for(p)
    off_blob = "".join(b93(x, off_width) for x in offs)

    base_id = ids[0]
    id_width = width_for(ids[-1] - base_id)
    ids_blob = "".join(b93(i - base_id, id_width) for i in ids)

    # python round-trip: decode everything back and compare
    def decode_recipe(pos):
        def take(w):
            nonlocal pos
            v = u93(data_blob, pos, w)
            pos += w
            return v
        out = {
            "profession": profession_vals[take(W["profession"]) - 1],
            "tier": take(W["tier"]), "category": take(W["category"]),
            "xp": take(W["xp"]), "cooldown": take(W["cooldown"]),
        }
        flags = take(W["flags"])
        out["guild"] = flags % 2 == 1
        out["single_use"] = flags % 4 >= 2
        out["conversion"] = flags >= 4
        sc = take(W["item"])
        pk = take(W["item"])
        out["scroll"] = sc and sc + ITEM_BASE or 0
        out["pack"] = pk and pk + ITEM_BASE or 0
        out["pack_count"] = take(W["pack_count"])
        out["versions"] = []
        for _ in range(take(W["n"])):
            v = {"crit": take(W["crit"]), "ing": [], "opt": [], "res": [], "cres": []}
            ni, no, nr, nc = take(W["n"]), take(W["n"]), take(W["n"]), take(W["n"])
            for _ in range(ni):
                v["ing"].append((take(W["item"]) + ITEM_BASE, take(W["qty"])))
            for _ in range(no):
                v["opt"].append((take(W["item"]) + ITEM_BASE, take(W["qty"]), take(W["bonus"])))
            for _ in range(nr):
                v["res"].append((take(W["item"]) + ITEM_BASE, take(W["qty"])))
            for _ in range(nc):
                v["cres"].append((take(W["item"]) + ITEM_BASE, take(W["qty"])))
            out["versions"].append(v)
        return out

    for n, i in enumerate(ids):
        got = decode_recipe(offs[n] - 1)
        src = recipes[i]
        for k in ("profession", "tier", "category", "xp", "cooldown", "guild",
                  "single_use", "conversion", "scroll", "pack", "pack_count", "versions"):
            if got[k] != src[k]:
                raise AssertionError("round-trip mismatch recipe %d field %s" % (i, k))
    print("round-trip: all %d recipes verified" % count)

    os.makedirs(out_dir, exist_ok=True)
    sizes = {}
    sizes["records.lua"] = write_file(out_dir, "records.lua", [
        emit_blob("IDS", ids_blob),
        emit_blob("OFF", off_blob),
        emit_blob("DATA", data_blob),
    ])

    # Localized name chain: recipe label -> result-item label (same lang) -> en.
    # The dump only emits a recipe label when it differs from the result item's
    # name, so the item-label fallback is the game-correct localization.
    def result_item_of(r):
        for v in r["versions"]:
            if v["res"]:
                return v["res"][0][0]
            if v["cres"]:
                return v["cres"][0][0]
        return 0

    result_items = [result_item_of(recipes[i]) for i in ids]
    if records is not None:
        # records already carry the per-language chain (recipe name ->
        # result item name); bake en where a language has nothing
        en_names = [recipes[i]["name"] or "" for i in ids]
        names_by_lang, baked_report = {}, {}
        for lang in langs:
            if lang == "en":
                names_by_lang[lang] = en_names
                baked_report[lang] = 0
                continue
            names, from_en = [], 0
            for n, i in enumerate(ids):
                v = recipes[i].get("name_" + lang)
                if v is None or v == "":
                    v = en_names[n]
                    from_en += 1
                names.append(v)
            names_by_lang[lang] = names
            baked_report[lang] = from_en
    else:
        labels_en = parse_labels(data_dir, "en", "recipes")
        en_names = [labels_en.get(i) or recipes[i]["name"] for i in ids]
        names_by_lang, baked_report = {}, {}
        for lang in langs:
            if lang == "en":
                names_by_lang[lang] = en_names
                baked_report[lang] = 0
                continue
            rec_lab = parse_labels(data_dir, lang, "recipes")
            item_lab = parse_labels(data_dir, lang, "items")
            names, from_en = [], 0
            for n, i in enumerate(ids):
                v = rec_lab.get(i) or item_lab.get(result_items[n])
                if v is None or v == "":
                    v = en_names[n]
                    from_en += 1
                names.append(v)
            names_by_lang[lang] = names
            baked_report[lang] = from_en
    missing_en = sum(1 for v in en_names if not v)
    lang_sizes, _ = emit_lang_files(out_dir, ids, names_by_lang, langs)
    sizes.update(lang_sizes)

    # crafting UI category names, per language (tiny plain table)
    used_cats = {r["category"] for r in recipes.values()}
    if aux is not None:
        cat_labels = aux["category_labels"]
    else:
        cat_enum = parse_enum(data_dir, "CraftingUICategory")
        en_cat_lab = parse_labels(data_dir, "en", "enum-CraftingUICategory", raw_keys=True)
        cat_labels = {}
        for lang in langs:
            lab = parse_labels(data_dir, lang, "enum-CraftingUICategory", raw_keys=True)
            table = {}
            for code, key in cat_enum.items():
                if key.startswith("key:"):
                    table[code] = lab.get(key) or en_cat_lab.get(key) or key
                else:
                    table[code] = key
            cat_labels[lang] = table
    cat_parts = ["D.CATS = {\n"]
    for lang in langs:
        entries = []
        for code in sorted(cat_labels["en"]):
            if code in used_cats:
                value = cat_labels[lang].get(code) or cat_labels["en"][code]
                entries.append("[%d]=%s" % (code, lua_string(value)))
        cat_parts.append("%s = { %s },\n" % (lang, ", ".join(entries)))
    cat_parts.append("}\n")

    # localized profession display names
    used_profs = set(profession_vals)
    if aux is not None:
        prof_labels = aux["profession_labels"]
        prof_defs = [(None, key, prof_labels["en"][key])
                     for key in sorted(prof_labels["en"])]
    else:
        prof_defs = []
        for _, el in ET.iterparse(os.path.join(data_dir, "crafting.xml")):
            if el.tag == "profession":
                prof_defs.append((int(el.get("identifier")), el.get("key"), el.get("name")))
                el.clear()
        en_prof_lab = parse_labels(data_dir, "en", "crafting")
        prof_labels = {}
        for lang in langs:
            lab = parse_labels(data_dir, lang, "crafting")
            prof_labels[lang] = {
                key: (lab.get(ident) or en_prof_lab.get(ident) or en_name)
                for ident, key, en_name in prof_defs}
    prof_parts = ["D.PROFS = {\n"]
    for lang in langs:
        entries = []
        for _ident, key, _en_name in prof_defs:
            if key in used_profs:
                value = prof_labels[lang].get(key) or prof_labels["en"][key]
                entries.append('["%s"] = %s' % (key, lua_string(value)))
        if len(entries) != len(used_profs):
            raise AssertionError("professions used by recipes are missing from the profession table")
        prof_parts.append("%s = { %s },\n" % (lang, ", ".join(entries)))
    prof_parts.append("}\n")

    sizes["categories.lua"] = write_file(out_dir, "categories.lua", cat_parts + prof_parts)
    missing_cats = sorted(c for c in used_cats if c not in cat_labels["en"] and c != 0)
    if missing_cats:
        print("WARNING: recipe categories missing from enum: %s" % missing_cats)

    sizes["manifest.lua"] = write_file(out_dir, "manifest.lua", [
        "D.count = %d\n" % count,
        "D.base_id = %d\n" % base_id,
        "D.id_width = %d\n" % id_width,
        "D.off_width = %d\n" % off_width,
        "D.item_base = %d\n" % ITEM_BASE,
        "D.widths = { %s }\n" % ", ".join(
            "%s = %d" % (k, W[k]) for k in sorted(W)),
        "D.enums = { profession = { %s } }\n" % ", ".join(
            lua_string(v) for v in profession_vals),
        "D.langs = { %s }\n" % ", ".join(lua_string(v) for v in langs),
    ])
    print_report(baked_report, missing_en, sizes, langs, count, t0)


# ------------------------------------------------------ quests + deeds ----

def convert_quests(out_dir, langs, records, aux):
    """Pack quests + deeds (game-extracted records): variable-length
    numeric records (levels, category, rewards, chains, flags),
    per-language labels/names/search blobs, per-language content blobs
    (description / objective texts / bestower dialog texts) and localized
    category tables."""
    t0 = time.time()
    # record order = display order: level, then folded EN name. Category
    # (zone) filters iterate records in file order and come out sorted by
    # level then name with zero runtime sorting; the search bar uses the
    # per-language alphabetical names blobs instead.
    ids = sorted(records, key=lambda i: (records[i]["level"],
                                         fold(display_sort_text(records[i]["name"])),
                                         records[i]["name"], i))
    count = len(ids)
    print("packing %d quest/deed records" % count)

    def quest_off(qid):
        if qid == 0:
            return 0
        off = qid - ITEM_BASE
        if off <= 0:
            raise AssertionError("quest id %d below base" % qid)
        return off

    # width maxes over the whole domain
    mx = {"level": 0, "category": 0, "tier": 0, "flags": 0, "times": 0,
          "lock": 0, "ref": 0, "qty": 0, "n": 0, "event": 0, "count": 0}
    for r in records.values():
        mx["level"] = max(mx["level"], r["level"], r["minLevel"])
        mx["category"] = max(mx["category"], r["category"])
        mx["tier"] = max(mx["tier"], r["expTier"], r["goldTier"],
                         r["virtueXpTier"])
        mx["flags"] = max(mx["flags"], r["flags"])
        mx["times"] = max(mx["times"], r["maxTimes"])
        mx["lock"] = max(mx["lock"], r["lockType"])
        mx["ref"] = max(mx["ref"], quest_off(r["nextQuest"]),
                        max((quest_off(q) for q in r["prereqs"]), default=0),
                        max((quest_off(i) for i, _q in r["rewards"]), default=0),
                        max((quest_off(n) for _o, _a, n in r["dialogNpcs"] if n),
                            default=0))
        mx["qty"] = max(mx["qty"], max((q for _i, q in r["rewards"]),
                                       default=0))
        mx["n"] = max(mx["n"], len(r["prereqs"]), len(r["rewards"]),
                      len(r["dialogNpcs"]), len(r["objectiveConds"]),
                      max((len(c) for c in r["objectiveConds"]), default=0),
                      max((o for o, _a, _n in r["dialogNpcs"]), default=0),
                      max((a for _o, a, _n in r["dialogNpcs"]), default=0))
        for conds in r["objectiveConds"]:
            for cond_event, cond_count in conds:
                mx["event"] = max(mx["event"], cond_event)
                mx["count"] = max(mx["count"], cond_count)

    W = {key: width_for(value) for key, value in mx.items()}
    W["deed"] = 1

    def encode(r):
        parts = [
            b93(1 if r["kind"] == "deed" else 0, W["deed"]),
            b93(r["level"], W["level"]),
            b93(r["minLevel"], W["level"]),
            b93(r["category"], W["category"]),
            b93(r["expTier"], W["tier"]),
            b93(r["goldTier"], W["tier"]),
            b93(r["virtueXpTier"], W["tier"]),
            b93(r["flags"], W["flags"]),
            b93(r["maxTimes"], W["times"]),
            b93(r["lockType"], W["lock"]),
            b93(quest_off(r["nextQuest"]), W["ref"]),
            b93(len(r["prereqs"]), W["n"]),
            b93(len(r["rewards"]), W["n"]),
            b93(len(r["dialogNpcs"]), W["n"]),
        ]
        for q in r["prereqs"]:
            parts.append(b93(quest_off(q), W["ref"]))
        for item, qty in r["rewards"]:
            parts.append(b93(quest_off(item), W["ref"]) + b93(qty, W["qty"]))
        for obj_idx, action, npc in r["dialogNpcs"]:
            parts.append(b93(obj_idx, W["n"]) + b93(action, W["n"])
                         + b93(quest_off(npc), W["ref"]))
        parts.append(b93(len(r["objectiveConds"]), W["n"]))
        for conds in r["objectiveConds"]:
            parts.append(b93(len(conds), W["n"]))
            for event, count in conds:
                parts.append(b93(event, W["event"]) + b93(count, W["count"]))
        return "".join(parts)

    encoded = [encode(records[i]) for i in ids]
    data_blob = "".join(encoded)
    offs, p = [], 1
    for e in encoded:
        offs.append(p)
        p += len(e)
    offs.append(p)
    off_width = width_for(p)
    off_blob = "".join(b93(x, off_width) for x in offs)

    base_id = min(ids)
    id_width = width_for(max(ids) - base_id)
    ids_blob = "".join(b93(i - base_id, id_width) for i in ids)

    # id lookup index: ids ascending (IDX) with the matching ordinal
    # (IDO) — records themselves are in display order, so ordinal_of
    # binary-searches these instead of IDS
    ord_width = width_for(count)
    by_id = sorted(range(count), key=lambda n: ids[n])
    idx_blob = "".join(b93(ids[n] - base_id, id_width) for n in by_id)
    ido_blob = "".join(b93(n + 1, ord_width) for n in by_id)
    for k in range(count):
        rid = u93(idx_blob, k * id_width, id_width) + base_id
        o = u93(ido_blob, k * ord_width, ord_width)
        if ids[o - 1] != rid:
            raise AssertionError("id index mismatch at position %d" % k)

    # round-trip: decode everything back and compare
    def decode(pos):
        def take(w):
            nonlocal pos
            v = u93(data_blob, pos, w)
            pos += w
            return v
        out = {}
        out["kind"] = "deed" if take(W["deed"]) else "quest"
        out["level"] = take(W["level"])
        out["minLevel"] = take(W["level"])
        out["category"] = take(W["category"])
        out["expTier"] = take(W["tier"])
        out["goldTier"] = take(W["tier"])
        out["virtueXpTier"] = take(W["tier"])
        out["flags"] = take(W["flags"])
        out["maxTimes"] = take(W["times"])
        out["lockType"] = take(W["lock"])
        ref = take(W["ref"])
        out["nextQuest"] = ref and ref + ITEM_BASE or 0
        np_, nr, nd = take(W["n"]), take(W["n"]), take(W["n"])
        out["prereqs"] = [take(W["ref"]) + ITEM_BASE for _ in range(np_)]
        out["rewards"] = [(take(W["ref"]) + ITEM_BASE, take(W["qty"]))
                          for _ in range(nr)]
        out["dialogNpcs"] = []
        for _ in range(nd):
            obj_idx = take(W["n"])
            action = take(W["n"])
            ref = take(W["ref"])
            out["dialogNpcs"].append((obj_idx, action,
                                      ref and ref + ITEM_BASE or 0))
        out["objectiveConds"] = []
        for _ in range(take(W["n"])):
            out["objectiveConds"].append(
                [(take(W["event"]), take(W["count"]))
                 for _ in range(take(W["n"]))])
        return out

    for n, i in enumerate(ids):
        got = decode(offs[n] - 1)
        src = records[i]
        for key in got:
            if got[key] != src[key]:
                raise AssertionError("round-trip mismatch %d field %s" % (i, key))
    print("round-trip: all %d records verified" % count)

    os.makedirs(out_dir, exist_ok=True)
    sizes = {}
    sizes["records.lua"] = write_file(out_dir, "records.lua", [
        emit_blob("IDS", ids_blob),
        emit_blob("IDX", idx_blob),
        emit_blob("IDO", ido_blob),
        emit_blob("OFF", off_blob),
        emit_blob("DATA", data_blob),
    ])

    # per-language content blobs: one entry per record;
    # sections (description / objectives / dialogs) separated by \\30,
    # texts within a section by \\31; within one objective the
    # description and its condition texts are separated by \\29
    SECTION_SEP = "\x1e"
    TEXT_SEP = "\x1f"
    SUB_SEP = "\x1d"
    for lang in langs:
        entries = []
        for i in ids:
            desc, objective_texts, dialog_texts = records[i]["text_" + lang]
            entries.append(SECTION_SEP.join([
                desc,
                TEXT_SEP.join(SUB_SEP.join(entry)
                              for entry in objective_texts),
                TEXT_SEP.join(dialog_texts)]))
        blob = "".join(entries)
        toffs, p = [], 1
        for e in entries:
            toffs.append(p)
            p += byte_len(e)
        toffs.append(p)
        toff_width = width_for(p)
        toff_blob = "".join(b93(x, toff_width) for x in toffs)
        sizes["texts_%s.lua" % lang] = write_file(
            out_dir, "texts_%s.lua" % lang, [
                "D.toff_width = %d\n" % toff_width,
                emit_blob("TXT", blob),
                emit_blob("TOFF", toff_blob),
            ])

    json_names = {i: {k[5:]: v for k, v in records[i].items()
                      if k.startswith("name_")} for i in ids}
    en_fallback = [records[i]["name"] for i in ids]
    names_by_lang, baked_report, missing_en = build_names_by_lang_records(
        json_names, langs, ids, en_fallback)
    lang_sizes, _ = emit_lang_files(out_dir, ids, names_by_lang, langs)
    sizes.update(lang_sizes)

    # per-language display-order permutations: the record order is
    # (level, folded en name), so en listings iterate ordinals directly;
    # de/fr get the same level order but their own name tie-break via an
    # ordinal permutation sorted by (level, folded local label)
    for lang in langs:
        if lang == "en":
            continue
        names = names_by_lang[lang]
        order = sorted(range(count),
                       key=lambda n: (records[ids[n]]["level"],
                                      fold(display_sort_text(names[n])),
                                      names[n], n))
        sizes["order_%s.lua" % lang] = write_file(
            out_dir, "order_%s.lua" % lang, [
                "D.ord_width = %d\n" % ord_width,
                emit_blob("ORD", "".join(b93(n + 1, ord_width)
                                         for n in order)),
            ])

    # localized category tables (used codes only), per kind
    used = {"quest": set(), "deed": set()}
    for i in ids:
        used[records[i]["kind"]].add(records[i]["category"])
    cat_parts = []
    for label_key, table_name in (("quest_category_labels", "QUEST_CATS"),
                                  ("deed_category_labels", "DEED_CATS")):
        labels = aux[label_key]
        kind = "quest" if table_name == "QUEST_CATS" else "deed"
        cat_parts.append("D.%s = {\n" % table_name)
        for lang in langs:
            entries = []
            for code in sorted(used[kind]):
                value = labels[lang].get(code) or labels["en"].get(code)
                if value is not None:
                    entries.append("[%d]=%s" % (code, lua_string(value)))
            cat_parts.append("%s = { %s },\n" % (lang, ", ".join(entries)))
        cat_parts.append("}\n")
        # dropdown code order per language, sorted by localized label
        cat_parts.append("D.%s_ORDER = {\n" % table_name)
        for lang in langs:
            def cat_label(code):
                return labels[lang].get(code) or labels["en"].get(code)
            codes = [c for c in sorted(used[kind]) if cat_label(c) is not None]
            codes.sort(key=lambda c: (fold(cat_label(c)), cat_label(c), c))
            cat_parts.append("%s = { %s },\n" % (
                lang, ", ".join(str(c) for c in codes)))
        cat_parts.append("}\n")
    sizes["categories.lua"] = write_file(out_dir, "categories.lua", cat_parts)

    sizes["manifest.lua"] = write_file(out_dir, "manifest.lua", [
        "D.count = %d\n" % count,
        "D.base_id = %d\n" % base_id,
        "D.id_width = %d\n" % id_width,
        "D.ord_width = %d\n" % ord_width,
        "D.off_width = %d\n" % off_width,
        "D.ref_base = %d\n" % ITEM_BASE,
        "-- record order: level ascending, then folded en name\n",
        "D.widths = { %s }\n" % ", ".join(
            "%s = %d" % (k, W[k]) for k in sorted(W)),
        # maxTimes: 0 = not repeatable, 1 = unlimited, n+1 = n times
        "D.section_sep = %s\n" % lua_string(SECTION_SEP),
        "D.text_sep = %s\n" % lua_string(TEXT_SEP),
        "D.sub_sep = %s\n" % lua_string(SUB_SEP),
        "D.langs = { %s }\n" % ", ".join(lua_string(v) for v in langs),
    ])
    print_report(baked_report, missing_en, sizes, langs, count, t0)


# ----------------------------------------------------------------- npcs ----

def convert_npcs(out_dir, langs, records):
    """Pack NPC id -> localized "name \\31 title" lookup blobs."""
    t0 = time.time()
    ids = sorted(records)
    count = len(ids)
    print("packing %d NPC records" % count)

    base_id = ids[0]
    id_width = width_for(ids[-1] - base_id)
    ids_blob = "".join(b93(i - base_id, id_width) for i in ids)

    os.makedirs(out_dir, exist_ok=True)
    sizes = {}
    sizes["records.lua"] = write_file(out_dir, "records.lua", [
        emit_blob("IDS", ids_blob),
    ])

    TEXT_SEP = "\x1f"
    for lang in langs:
        suffix = "" if lang == "en" else "_" + lang
        entries = []
        for i in ids:
            r = records[i]
            name = r["name" + suffix] if lang != "en" else r["name"]
            title = r["title" + suffix] if lang != "en" else r["title"]
            if not name:
                name = r["name"]  # en fallback
            entries.append(name + (TEXT_SEP + title if title else ""))
        blob = "".join(entries)
        offs, p = [], 1
        for e in entries:
            offs.append(p)
            p += byte_len(e)
        offs.append(p)
        off_width = width_for(p)
        off_blob = "".join(b93(x, off_width) for x in offs)
        sizes["labels_%s.lua" % lang] = write_file(
            out_dir, "labels_%s.lua" % lang, [
                "D.loff_width = %d\n" % off_width,
                emit_blob("LBL", blob),
                emit_blob("LOFF", off_blob),
            ])

    sizes["manifest.lua"] = write_file(out_dir, "manifest.lua", [
        "D.count = %d\n" % count,
        "D.base_id = %d\n" % base_id,
        "D.id_width = %d\n" % id_width,
        "D.text_sep = %s\n" % lua_string(TEXT_SEP),
        "D.langs = { %s }\n" % ", ".join(lua_string(v) for v in langs),
    ])
    total = 0
    print("emitted files:")
    for name in sorted(sizes):
        total += sizes[name]
        print("  %-18s %8.2f MB" % (name, sizes[name] / 1e6))
    print("  %-18s %8.2f MB" % ("TOTAL", total / 1e6))
    print("done in %.1fs\n" % (time.time() - t0))


# ------------------------------------------------------------- bestiary ----
# Packs the wiki bestiary (src/Encyclopedia/data.lua, dumped to JSON by
# bestiary_dump.lua) into blobs. The decode layer reproduces the raw
# data.lua entry shape exactly; lookup/group indexes replicate the
# semantics of src/Encyclopedia/data_access.lua and are baked at build time.

B_SCALARS = ["n", "bn", "tl", "v", "g", "s", "sp", "r", "a", "i", "t"]
B_CE = ["f", "fm", "sm", "rt"]
B_RS = ["cr", "so", "ta", "ph"]
B_MI = ["co", "ad", "fi", "be", "li", "we", "sh", "fr", "lt"]
B_LISTS = ["ab", "qi", "di", "w", "cw"]

_LUA_SPACE = " \t\n\r\f\v"


def _lua_trim(s):
    return s.strip(_LUA_SPACE)


def _lua_lower(s):
    # Lua 5.1 string.lower is ASCII-only; replicate exactly
    return "".join(chr(ord(c) + 32) if "A" <= c <= "Z" else c for c in s)


def _lua_normalize_name(name):
    name = _lua_trim(name)
    if name == "":
        return None
    if _lua_lower(name)[:4] == "the ":
        name = _lua_trim(name[4:])
    import re as _re
    name = _re.sub(r"[ \t\n\r\f\v]*\.+$", "", name)
    name = _lua_trim(name)
    if name == "":
        return None
    return name


def _lua_normalized_lower(name):
    normalized = _lua_normalize_name(name)
    if normalized is not None:
        return _lua_lower(normalized)
    return _lua_lower(_lua_trim(name))


# localized target-name bridge: join wiki base names to mobs.xml, emit
# per-language {normalized localized name -> English base name} maps. 96%
# of wiki names match exactly; wiki disambiguation suffixes are stripped
# as a fallback. Identity translations are skipped (the English index
# already resolves them), and everything else falls back to English.
# D.display is the inverse ({English base name -> localized}) for the
# render-time name swap; keys/cache/index stay English underneath.
def _emit_bestiary_name_bridge(data_dir, out_dir, entries):
    mob_ids_by_name = {}
    for m in re.finditer(r'<mob id="(\d+)" name="([^"]*)"',
                         open(os.path.join(data_dir, "mobs.xml"), encoding="utf-8").read()):
        mob_ids_by_name.setdefault(m.group(2), []).append(int(m.group(1)))

    base_names = {}
    for key, entry in entries.items():
        if "alias" not in entry:
            base_names[entry.get("bn") or key] = True

    def match_ids(bn):
        ids = mob_ids_by_name.get(bn)
        if ids is None:
            ids = mob_ids_by_name.get(re.sub(r"\s*\([^)]*\)$", "", bn))
        return ids

    for lang in ("fr", "de"):
        labels = parse_labels(data_dir, lang, "mobs")
        mapping = {}
        display = {}
        matched, collisions = 0, 0
        for bn in base_names:
            ids = match_ids(bn)
            if not ids:
                continue
            for mob_id in ids:
                localized = labels.get(mob_id)
                if localized:
                    matched += 1
                    if localized != bn:
                        display[bn] = localized
                    lookup = _lua_normalized_lower(localized)
                    if lookup != _lua_normalized_lower(bn):
                        if lookup in mapping and mapping[lookup] != bn:
                            collisions += 1
                        else:
                            mapping[lookup] = bn
                    break
        parts = ["D.map = {\n"]
        for lookup in sorted(mapping):
            parts.append("[%s] = %s,\n" % (lua_string(lookup), lua_string(mapping[lookup])))
        parts.append("}\n")
        parts.append("D.display = {\n")
        for bn in sorted(display):
            parts.append("[%s] = %s,\n" % (lua_string(bn), lua_string(display[bn])))
        parts.append("}\n")
        write_file(out_dir, "names_%s.lua" % lang, parts)
        print("bestiary name bridge %s: %d matched, %d bridged, %d display, %d collisions dropped"
              % (lang, matched, len(mapping), len(display), collisions))


# localized string pools: pool_fr/pool_de mirror pool.lua entry-for-entry
# (same indices), with strings replaced where a game-data label joins to the
# English text. Name fields (n/bn/tl) always stay English: the resolution
# index, group keys and the observation cache are keyed by them. Ratings
# (ce/rs/mi) have no label source in the dump and stay English this phase.
_B_POOL_GROUP_OF_SCALAR = {
    "g": "genus", "s": "species", "sp": "subspecies",
    "r": "location", "a": "location", "v": "location", "i": "location",
    "t": "tier",
}
_B_POOL_GROUPS = ("genus", "species", "subspecies", "tier", "location",
                  "ability", "quest", "deed", "item", "rating")
_B_QI_PREFIX_RE = re.compile(r"^(-?\s*\[[^\]]*\]\s*)(.*)$")
_B_SUFFIX_RE = re.compile(r"^(.*?)(\s*\([^)]*\))$")


def _emit_bestiary_localized_pools(data_dir, out_dir, entries, record_keys,
                                   pool, pool_ref):
    protected = set()
    group_indices = {g: set() for g in _B_POOL_GROUPS}
    for key in record_keys:
        entry = entries[key]
        for f in ("n", "bn", "tl"):
            if f in entry:
                protected.add(pool_ref[entry[f]])
        for f, group in _B_POOL_GROUP_OF_SCALAR.items():
            if f in entry:
                group_indices[group].add(pool_ref[entry[f]])
        for m in ("ce", "rs", "mi"):
            for v in entry.get(m, {}).values():
                group_indices["rating"].add(pool_ref[v])
        for f, group in (("ab", "ability"), ("qi", "quest"), ("di", "deed"),
                         ("w", "item"), ("cw", "item")):
            for v in entry.get(f, []):
                group_indices[group].add(pool_ref[v])

    def key_joined(lang, db):
        # label-key join (enum labels): EN value -> localized value;
        # identity hits kept so coverage reflects "a label exists"
        en = parse_labels(data_dir, "en", db, raw_keys=True)
        loc = parse_labels(data_dir, lang, db, raw_keys=True)
        out = {}
        for k, en_v in en.items():
            lv = loc.get(k)
            if lv:
                out.setdefault(en_v, lv)
        return out

    def id_joined(lang, db):
        # same-id join: EN name -> localized name, majority on conflicts
        en = parse_labels(data_dir, "en", db, raw_keys=True)
        loc = parse_labels(data_dir, lang, db, raw_keys=True)
        votes = {}
        for k, en_v in en.items():
            lv = loc.get(k)
            if lv:
                votes.setdefault(en_v, {})
                votes[en_v][lv] = votes[en_v].get(lv, 0) + 1
        return {en_v: max(sorted(c), key=c.get) for en_v, c in votes.items()}

    def merged(*dicts):
        out = {}
        for d in dicts:
            for k, v in d.items():
                out.setdefault(k, v)
        return out

    sizes = {}
    for lang in ("fr", "de"):
        quest_dict = id_joined(lang, "quests")
        dicts = {
            "genus": key_joined(lang, "enum-Genus"),
            "species": key_joined(lang, "enum-Species"),
            "subspecies": key_joined(lang, "enum-SubSpecies"),
            "tier": key_joined(lang, "enum-MobType"),
            # wiki location strings mix areas, dungeons, instances,
            # landmarks and quest-instance names
            "location": merged(id_joined(lang, "geoAreas"),
                               id_joined(lang, "dungeons"),
                               id_joined(lang, "instances"),
                               id_joined(lang, "landmarks"),
                               quest_dict),
            "ability": merged(id_joined(lang, "effects"),
                              id_joined(lang, "skills")),
            "quest": quest_dict,
            "deed": id_joined(lang, "deeds"),
            "item": id_joined(lang, "items"),
            "rating": {},
        }

        def base_translate(group, s):
            d = dicts[group]
            hit = d.get(s)
            if hit:
                return hit
            if group in ("quest", "location"):
                # qi strings are "[level] Name" (some "- [level] Name")
                m = _B_QI_PREFIX_RE.match(s)
                if m:
                    hit = d.get(m.group(2))
                    if hit:
                        return m.group(1) + hit
            # wiki disambiguation suffixes: translate base, keep suffix
            m = _B_SUFFIX_RE.match(s)
            if m:
                hit = d.get(m.group(1))
                if hit:
                    return hit + m.group(2)
            return None

        def translate(group, s):
            hit = base_translate(group, s)
            if hit:
                return hit
            if " / " in s:
                parts = [base_translate(group, p) for p in s.split(" / ")]
                if all(parts):
                    return " / ".join(parts)
            return None

        localized = list(pool)
        changed = 0
        report = []
        for group in _B_POOL_GROUPS:
            indices = group_indices[group] - protected
            hits = 0
            for idx in sorted(indices):
                translation = translate(group, pool[idx - 1])
                if translation is None:
                    continue
                hits += 1
                if translation != pool[idx - 1] and localized[idx - 1] == pool[idx - 1]:
                    localized[idx - 1] = translation
                    changed += 1
            if indices:
                report.append("%s %d/%d" % (group, hits, len(indices)))

        pool_blob = "".join(localized)
        poffs, pos = [], 1
        for v in localized:
            poffs.append(pos)
            pos += byte_len(v)
        poffs.append(pos)
        poff_w = width_for(pos)
        poff_blob = "".join(b93(x, poff_w) for x in poffs)
        name = "pool_%s.lua" % lang
        sizes[name] = write_file(out_dir, name, [
            "D.poff_width = %d\n" % poff_w,
            emit_blob("POOL", pool_blob),
            emit_blob("POFF", poff_blob),
        ])
        print("bestiary pool %s: %d/%d strings localized (%d name-protected)"
              % (lang, changed, len(pool), len(protected)))
        print("  coverage: " + ", ".join(report))
    return sizes


def convert_bestiary(json_path, out_dir, data_dir=None):
    import json as _json
    t0 = time.time()
    with open(json_path, encoding="utf-8") as f:
        entries = _json.load(f)["entries"]
    keys = sorted(entries)
    print("bestiary source: %d entries" % len(keys))

    aliases = {}
    record_keys = []
    for key in keys:
        entry = entries[key]
        if "alias" in entry:
            target = _lua_trim(entry["alias"])
            for lookup in (_lua_lower(key), _lua_normalized_lower(key)):
                aliases.setdefault(lookup, target)
        else:
            record_keys.append(key)
    count = len(record_keys)

    # one shared string pool for every string value
    pool_set = set()
    for key in record_keys:
        entry = entries[key]
        for f in B_SCALARS:
            if f in entry:
                pool_set.add(entry[f])
        for m, subs in (("ce", B_CE), ("rs", B_RS), ("mi", B_MI)):
            for sub in entry.get(m, {}).values():
                pool_set.add(sub)
        for f in B_LISTS:
            for v in entry.get(f, []):
                pool_set.add(v)
    pool = sorted(pool_set)
    pool_ref = {v: i + 1 for i, v in enumerate(pool)}
    ref_w = width_for(len(pool))

    l_w = width_for(max((e["l"][1] for e in entries.values() if "l" in e), default=0) + 1)
    m_w = width_for(max((e["m"][1] for e in entries.values() if "m" in e), default=0) + 1)
    p_w = width_for(max((e["p"][1] for e in entries.values() if "p" in e), default=0) + 1)

    def encode_entry(entry):
        parts = []
        for f in B_SCALARS:
            parts.append(b93(pool_ref[entry[f]] if f in entry else 0, ref_w))
        for f, w in (("l", l_w), ("m", m_w), ("p", p_w)):
            if f in entry:
                parts.append(b93(entry[f][0] + 1, w))
                parts.append(b93(entry[f][1] + 1, w))
            else:
                parts.append(b93(0, w))
                parts.append(b93(0, w))
        for m, subs in (("ce", B_CE), ("rs", B_RS), ("mi", B_MI)):
            mv = entry.get(m, {})
            for sub in subs:
                parts.append(b93(pool_ref[mv[sub]] if sub in mv else 0, ref_w))
        for f in B_LISTS:
            values = entry.get(f, [])
            parts.append(b93(len(values), 1))
            for v in values:
                parts.append(b93(pool_ref[v], ref_w))
        return "".join(parts)

    encoded = [encode_entry(entries[k]) for k in record_keys]
    data_blob = "".join(encoded)
    offs, pos = [], 1
    for e in encoded:
        offs.append(pos)
        pos += len(e)
    offs.append(pos)
    off_w = width_for(pos)
    off_blob = "".join(b93(x, off_w) for x in offs)

    keys_blob = "".join(record_keys)
    koffs, pos = [], 1
    for k in record_keys:
        koffs.append(pos)
        pos += byte_len(k)
    koffs.append(pos)
    koff_w = width_for(pos)
    koff_blob = "".join(b93(x, koff_w) for x in koffs)

    pool_blob = "".join(pool)
    poffs, pos = [], 1
    for v in pool:
        poffs.append(pos)
        pos += byte_len(v)
    poffs.append(pos)
    poff_w = width_for(pos)
    poff_blob = "".join(b93(x, poff_w) for x in poffs)

    ord_w = width_for(count)

    # lookup index: raw_lower and normalized_lower of every key -> ordinal;
    # deterministic first-in-sorted-key-order wins on collisions
    lookup_map = {}
    for n, key in enumerate(record_keys):
        for lookup in (_lua_lower(key), _lua_normalized_lower(key)):
            if lookup != "" and lookup not in lookup_map:
                lookup_map[lookup] = n + 1
    lookup_parts, loffs, pos = [], [], 1
    for lookup in sorted(lookup_map):
        part = "\n%s\t%s" % (lookup, b93(lookup_map[lookup], ord_w))
        loffs.append(pos)
        lookup_parts.append(part)
        pos += byte_len(part)
    lookup_blob = "".join(lookup_parts) + "\n"
    loff_w = width_for(pos)
    loff_blob = "".join(b93(x, loff_w) for x in loffs)

    # group index: normalized-lower base name -> ordinals (sorted-key order)
    groups = {}
    for n, key in enumerate(record_keys):
        entry = entries[key]
        base = entry.get("bn") or entry.get("n") or key
        base_lower = _lua_normalized_lower(base)
        groups.setdefault(base_lower, []).append(n + 1)
    group_parts, goffs, pos = [], [], 1
    for base in sorted(groups):
        part = "\n%s\t%s" % (base, "".join(b93(o, ord_w) for o in groups[base]))
        goffs.append(pos)
        group_parts.append(part)
        pos += byte_len(part)
    groups_blob = "".join(group_parts) + "\n"
    goff_w = width_for(pos)
    goff_blob = "".join(b93(x, goff_w) for x in goffs)

    # python round-trip: decode every record and compare to the source
    def decode_entry(n):
        pos = offs[n] - 1
        out = {}

        def take(w):
            nonlocal pos
            v = u93(data_blob, pos, w)
            pos += w
            return v

        for f in B_SCALARS:
            ref = take(ref_w)
            if ref:
                out[f] = pool[ref - 1]
        for f, w in (("l", l_w), ("m", m_w), ("p", p_w)):
            lo, hi = take(w), take(w)
            if lo or hi:
                out[f] = [lo - 1, hi - 1]
        for m, subs in (("ce", B_CE), ("rs", B_RS), ("mi", B_MI)):
            mv = {}
            for sub in subs:
                ref = take(ref_w)
                if ref:
                    mv[sub] = pool[ref - 1]
            if mv:
                out[m] = mv
        for f in B_LISTS:
            n_items = take(1)
            if n_items:
                out[f] = [pool[take(ref_w) - 1] for _ in range(n_items)]
        return out

    for n, key in enumerate(record_keys):
        if decode_entry(n) != entries[key]:
            raise AssertionError("bestiary round-trip mismatch: " + key)
    print("round-trip: all %d records verified (+%d aliases)" % (count, len(aliases)))
    os.makedirs(out_dir, exist_ok=True)
    sizes = {}
    if data_dir:
        _emit_bestiary_name_bridge(data_dir, out_dir, entries)
        sizes.update(_emit_bestiary_localized_pools(
            data_dir, out_dir, entries, record_keys, pool, pool_ref))
    sizes["records.lua"] = write_file(out_dir, "records.lua", [
        emit_blob("DATA", data_blob),
        emit_blob("OFF", off_blob),
        emit_blob("KEYS", keys_blob),
        emit_blob("KOFF", koff_blob),
    ])
    sizes["pool.lua"] = write_file(out_dir, "pool.lua", [
        "D.poff_width = %d\n" % poff_w,
        emit_blob("POOL", pool_blob),
        emit_blob("POFF", poff_blob),
    ])
    sizes["index.lua"] = write_file(out_dir, "index.lua", [
        "D.lookup_count = %d\n" % len(lookup_map),
        "D.group_count = %d\n" % len(groups),
        emit_blob("LOOKUP", lookup_blob),
        emit_blob("LOFF", loff_blob),
        emit_blob("GROUPS", groups_blob),
        emit_blob("GOFF", goff_blob),
    ])
    alias_lines = ["D.aliases = {\n"]
    for lookup in sorted(aliases):
        alias_lines.append("[%s] = %s,\n" % (lua_string(lookup), lua_string(aliases[lookup])))
    alias_lines.append("}\n")
    sizes["manifest.lua"] = write_file(out_dir, "manifest.lua", [
        "D.count = %d\n" % count,
        "D.ref_width = %d\n" % ref_w,
        "D.ord_width = %d\n" % ord_w,
        "D.off_width = %d\n" % off_w,
        "D.koff_width = %d\n" % koff_w,
        "D.loff_width = %d\n" % loff_w,
        "D.goff_width = %d\n" % goff_w,
        "D.l_width = %d\n" % l_w,
        "D.m_width = %d\n" % m_w,
        "D.p_width = %d\n" % p_w,
    ] + alias_lines)

    total = 0
    print("emitted files:")
    for name in sorted(sizes):
        total += sizes[name]
        print("  %-14s %8.2f MB" % (name, sizes[name] / 1e6))
    print("  %-14s %8.2f MB" % ("TOTAL", total / 1e6))
    print("done in %.1fs\n" % (time.time() - t0))


# ---------------------------------------------------------------- nodes ----
# Harvest/resource nodes: world objects the player collects from (deposits,
# branches, crop fields, artifacts). Each node is a profession-gated item in
# items.xml (requiredProfession="<prof_item_id>;<tier>") that also appears in
# containers.xml; its yields resolve through loots.xml trophy lists (repeated
# independent rolls: dropFrequency x quantity) and treasure lists (each entry
# is one guaranteed weighted pick from an <itemsTable>).
#
# Output is one small plain-Lua file (a few hundred nodes): localized node
# name -> item id lookup, per-node yields with quantity ranges and a band
# (1 = guaranteed, 2 = bonus, 3 = rare), localized profession/tier names and
# the per-profession-tier badge icon layers.

NODE_RARE_FREQ = 0.02


def convert_nodes(data_dir, out_dir, langs):
    t0 = time.time()

    # profession-gated items: id -> (profession item id, tier)
    req = {}
    for _, el in ET.iterparse(os.path.join(data_dir, "items.xml")):
        if el.tag == "item":
            rp = el.get("requiredProfession")
            if rp:
                parts = rp.split(";")
                tier = int(parts[1]) if len(parts) > 1 else 0
                req[int(el.get("key"))] = (int(parts[0]), tier)
            el.clear()

    # profession id -> key ("PROSPECTOR"), plus tier badge icon layers
    prof_key, prof_defs, icons = {}, [], {}
    cur_prof = None
    for ev, el in ET.iterparse(os.path.join(data_dir, "crafting.xml"), events=("start", "end")):
        # vocation blocks cross-reference professions as bare
        # <profession identifier="..."/>; only keyed elements define one
        if ev == "start" and el.tag == "profession" and el.get("key"):
            cur_prof = el.get("key")
            prof_key[int(el.get("identifier"))] = cur_prof
            prof_defs.append((int(el.get("identifier")), cur_prof, el.get("name")))
            icons[cur_prof] = {}
        elif ev == "end" and el.tag == "professionTier":
            if el.get("icon"):
                icons[cur_prof][int(el.get("identifier"))] = el.get("icon")
            el.clear()

    # loots.xml: trophy lists, treasure lists, weighted items tables
    trophy, treasure, tables = {}, {}, {}
    cur_list = None
    for ev, el in ET.iterparse(os.path.join(data_dir, "loots.xml"), events=("start", "end")):
        if ev == "start":
            if el.tag in ("trophyList", "treasureList", "itemsTable"):
                cur_list = []
                {"trophyList": trophy, "treasureList": treasure,
                 "itemsTable": tables}[el.tag][int(el.get("id"))] = cur_list
        else:
            if el.tag == "trophyListEntry" and el.get("itemId"):
                cur_list.append((float(el.get("dropFrequency")),
                                 int(el.get("itemId")), int(el.get("quantity") or 1)))
            elif el.tag == "treasureListEntry" and el.get("treasureGroupProfileId"):
                cur_list.append(int(el.get("treasureGroupProfileId")))
            elif el.tag == "itemsTableEntry" and el.get("itemId"):
                cur_list.append((int(el.get("itemId")), int(el.get("quantity") or 1)))
            if el.tag in ("trophyList", "treasureList", "itemsTable"):
                cur_list = None
            el.clear()

    # containers.xml join: profession-gated container objects are the nodes
    nodes = {}
    multi_table_alternatives = 0
    for _, el in ET.iterparse(os.path.join(data_dir, "containers.xml")):
        if el.tag != "container":
            continue
        cid = int(el.get("id"))
        if cid in req:
            # item id -> [min, max, best frequency]
            agg = {}

            def roll(iid, qty, freq):
                a = agg.setdefault(iid, [0, 0, 0.0])
                if freq >= 1.0:
                    a[0] += qty
                a[1] += qty
                a[2] = max(a[2], freq)

            tl = el.get("trophyListId")
            for freq, iid, qty in trophy.get(int(tl), []) if tl else []:
                roll(iid, qty, freq)
            trl = el.get("treasureListId")
            for gid in treasure.get(int(trl), []) if trl else []:
                entries = tables[gid]
                if len(entries) == 1:
                    roll(entries[0][0], entries[0][1], 1.0)
                else:
                    multi_table_alternatives += 1
                    for iid, qty in entries:
                        roll(iid, qty, 0.5)
            if agg:
                pid, tier = req[cid]
                yields = []
                for iid, (mn, mx, freq) in agg.items():
                    band = 1 if mn > 0 else (3 if freq < NODE_RARE_FREQ else 2)
                    yields.append((band, -mx, iid, mn, mx))
                yields.sort()
                nodes[cid] = (prof_key[pid], tier, yields)
        el.clear()
    print("nodes: %d (multi-item treasure tables: %d)" % (len(nodes), multi_table_alternatives))

    # localized node names -> item id (bytewise-exact target-name lookup);
    # missing localized labels fall back to the English name so lookups on
    # partially translated clients still resolve
    node_ids = sorted(nodes)
    en_lab = parse_labels(data_dir, "en", "items")
    name_parts = ["D.NAMES = {\n"]
    duplicate_names = 0
    for lang in langs:
        lab = en_lab if lang == "en" else parse_labels(data_dir, lang, "items")
        entries = {}
        for iid in node_ids:
            name = lab.get(iid) or en_lab.get(iid)
            if not name:
                raise AssertionError("node item %d has no English label" % iid)
            if name in entries:
                duplicate_names += 1
            entries[name] = iid
        name_parts.append("%s = {\n" % lang)
        for name in sorted(entries):
            name_parts.append("[%s] = %d,\n" % (lua_string(name), entries[name]))
        name_parts.append("},\n")
    name_parts.append("}\n")
    if duplicate_names:
        print("WARNING: %d duplicate node names collapsed" % duplicate_names)

    # per-node records
    node_parts = ["D.NODES = {\n"]
    for iid in node_ids:
        key, tier, yields = nodes[iid]
        ys = ", ".join("{%d, %d, %d, %d}" % (y[2], y[3], y[4], y[0]) for y in yields)
        node_parts.append('[%d] = { p = "%s", t = %d, y = { %s } },\n' % (iid, key, tier, ys))
    node_parts.append("}\n")

    # localized profession names (same source as the recipes domain)
    used_profs = {nodes[i][0] for i in node_ids}
    en_prof_lab = parse_labels(data_dir, "en", "crafting")
    prof_parts = ["D.PROFS = {\n"]
    for lang in langs:
        lab = parse_labels(data_dir, lang, "crafting")
        entries = []
        for ident, key, en_name in prof_defs:
            if key in used_profs:
                value = lab.get(ident) or en_prof_lab.get(ident) or en_name
                entries.append('["%s"] = %s' % (key, lua_string(value)))
        if len(entries) != len(used_profs):
            raise AssertionError("crafting.xml is missing professions used by nodes")
        prof_parts.append("%s = { %s },\n" % (lang, ", ".join(entries)))
    prof_parts.append("}\n")

    # localized crafting tier names (CraftTier enum labels)
    tier_enum = parse_enum(data_dir, "CraftTier")
    used_tiers = sorted({nodes[i][1] for i in node_ids})
    en_tier_lab = parse_labels(data_dir, "en", "enum-CraftTier", raw_keys=True)
    tier_parts = ["D.TIERS = {\n"]
    for lang in langs:
        lab = parse_labels(data_dir, lang, "enum-CraftTier", raw_keys=True)
        entries = []
        for code in used_tiers:
            enum_key = tier_enum[code]
            value = lab.get(enum_key) or en_tier_lab.get(enum_key) or enum_key
            entries.append("[%d] = %s" % (code, lua_string(value)))
        tier_parts.append("%s = { %s },\n" % (lang, ", ".join(entries)))
    tier_parts.append("}\n")

    # tier badge icon layers, professions used by nodes only
    icon_parts = ["D.ICONS = {\n"]
    for key in sorted(used_profs):
        tiers = icons[key]
        entries = []
        for tier in sorted(tiers):
            layers = ", ".join(tiers[tier].split("-"))
            entries.append("[%d] = { %s }" % (tier, layers))
        icon_parts.append('["%s"] = { %s },\n' % (key, ", ".join(entries)))
    icon_parts.append("}\n")

    size = write_file(out_dir, "nodes.lua", name_parts + node_parts + prof_parts + tier_parts + icon_parts)
    print("nodes.lua: %d bytes (%.1fs)" % (size, time.time() - t0))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", required=True, help=".data/lore directory")
    ap.add_argument("--out", required=True, help="output directory for generated Lua")
    ap.add_argument("--db", default="items,recipes", help="comma list: items,recipes,bestiary,nodes")
    ap.add_argument("--langs", default=",".join(LANGS))
    ap.add_argument("--bestiary-json",
                    default=os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                         os.pardir, os.pardir, ".tools",
                                         "bestiary_source.json"),
                    help="JSON produced by bestiary_dump.lua from src/Encyclopedia/data.lua")
    args = ap.parse_args()
    langs = args.langs.split(",")
    for db in args.db.split(","):
        if db == "items":
            convert_items(args.data, os.path.join(args.out, "Items"), langs)
        elif db == "recipes":
            convert_recipes(args.data, os.path.join(args.out, "Recipes"), langs)
        elif db == "bestiary":
            convert_bestiary(args.bestiary_json, os.path.join(args.out, "Bestiary"), args.data)
        elif db == "nodes":
            convert_nodes(args.data, os.path.join(args.out, "Nodes"), langs)
        else:
            raise SystemExit("unknown db: " + db)


if __name__ == "__main__":
    main()
