-- GENERATED by LUI data tools -- DO NOT EDIT
-- Source: LOTRO game client data
local D = {}
D.count = 8512
D.base_id = 1879048194
D.id_width = 3
D.text_sep = ""
D.langs = { "de", "en", "fr" }
_G.LoreData = _G.LoreData or {}
_G.LoreData["Npcs.manifest"] = D
return D
