-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.

-- the builtin wiki bestiary is packed (src/Data/Bestiary, generated by
-- tools/lore2lua from src/Bestiary/data.lua); bestiary_db registers a proxy
-- at DB.en.bestiary and loads the blobs on first access
import "LUI.src.Data.bestiary_db"
import "LUI.src.Bestiary.drop_table"
pcall(import, "LUI.src.Bestiary.drop_table_de")
pcall(import, "LUI.src.Bestiary.drop_table_fr")
import "LUI.src.Bestiary.data_resolver"
import "LUI.src.Bestiary.data_access"
import "LUI.src.Bestiary.card_widgets"
import "LUI.src.Bestiary.bestiary_card"
import "LUI.src.Bestiary.resource_card"
import "LUI.src.Bestiary.bestiary_tracker"
import "LUI.src.Bestiary.item_browser"
import "LUI.src.Bestiary.bestiary_window"
