-- GENERATED by tools/lore2lua -- DO NOT EDIT
-- Source: LotRO Companion lotro-data XML dumps
local D = {}
D.count = 149710
D.base_id = 1879049233
D.id_width = 3
D.stride = 14
D.poff_width = 3
D.fields = { "quality", "level", "class", "category", "slot", "icon", "min_level" }
D.widths = { 1, 2, 4, 1, 1, 3, 2 }
D.enums = {
quality = { "COMMON", "INCOMPARABLE", "LEGENDARY", "RARE", "UNCOMMON" },
category = { "ARMOUR", "CARRY_ALL", "ESSENCE", "ITEM", "LEGENDARY_ITEM", "LEGENDARY_ITEM2", "LEGENDARY_WEAPON", "LEGENDARY_WEAPON2", "WEAPON" },
slot = { "AURA", "BACK", "BRIDLE", "CHEST", "CLASS_SLOT", "EAR", "EITHER_HAND", "FEET", "FINGER", "HAND", "HEAD", "LEFT_EAR", "LEFT_FINGER", "LEFT_WRIST", "LEGS", "MAIN_HAND", "NECK", "OFF_HAND", "POCKET", "RANGED_ITEM", "RIGHT_EAR", "RIGHT_FINGER", "RIGHT_WRIST", "SHOULDER", "TOOL", "WRIST" },
}
D.langs = { "de", "en", "es", "fr", "ru" }
_G.LoreData = _G.LoreData or {}
_G.LoreData["Items.manifest"] = D
return D
